-- Ledge – Legislative AI Monitoring Platform
-- Run these ALTER statements on your existing Supabase project.
-- They are additive only (no DROP TABLE).

-- =============================================
-- 1. Extend the existing `legislation` table
-- =============================================
ALTER TABLE legislation ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'federal';
ALTER TABLE legislation ADD COLUMN IF NOT EXISTS state_code TEXT;

CREATE INDEX IF NOT EXISTS idx_legislation_source ON legislation(source);
CREATE INDEX IF NOT EXISTS idx_legislation_state_code ON legislation(state_code);

-- =============================================
-- 2. Extend the existing `subscribers` table
-- =============================================
ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS org_goal TEXT;
ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS state_focus TEXT;
ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS last_notified_id TEXT;

CREATE INDEX IF NOT EXISTS idx_subscribers_state_focus ON subscribers(state_focus);

-- =============================================
-- 3. New table: bill_matches
--    Stores per-subscriber relevance scores generated by the AI.
-- =============================================
CREATE TABLE IF NOT EXISTS bill_matches (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    subscriber_id UUID NOT NULL REFERENCES subscribers(id) ON DELETE CASCADE,
    legislation_id UUID NOT NULL REFERENCES legislation(id) ON DELETE CASCADE,
    match_score INTEGER NOT NULL DEFAULT 0,   -- 0-100
    summary TEXT,                              -- 2-sentence AI summary
    why_it_matters TEXT,                       -- org-specific explanation
    implications TEXT,                         -- potential downstream effects
    notified BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now(),

    UNIQUE(subscriber_id, legislation_id)
);

CREATE INDEX IF NOT EXISTS idx_bill_matches_subscriber ON bill_matches(subscriber_id);
CREATE INDEX IF NOT EXISTS idx_bill_matches_score ON bill_matches(match_score DESC);
CREATE INDEX IF NOT EXISTS idx_bill_matches_notified ON bill_matches(notified) WHERE notified = false;
